const popular = [
    {
        title: `16 Best Foods with Potassium for All Diets`,
        resim: 'https://www.gazetekars.com/d/news/45490.jpg',
        time: '15 hour',
        content: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquam sem et tortor consequat id porta. Feugiat sed lectus vestibulum mattis ullamcorper velit sed. A diam sollicitudin tempor id eu. Commodo odio aenean sed adipiscing diam donec adipiscing tristique. Nunc pulvinar sapien et ligula ullamcorper malesuada proin libero. Semper auctor neque vitae tempus quam. Ullamcorper eget nulla facilisi etiam dignissim diam quis enim lobortis. Amet tellus cras adipiscing enim eu turpis egestas pretium. Viverra justo nec ultrices dui sapien eget mi proin sed. Auctor elit sed vulputate mi sit.

        Donec massa sapien faucibus et molestie. Mollis nunc sed id semper risus in hendrerit gravida rutrum. Tortor at risus viverra adipiscing at in tellus. Sed felis eget velit aliquet sagittis. Suspendisse in est ante in nibh mauris cursus mattis molestie. Suspendisse sed nisi lacus sed viverra. Et malesuada fames ac turpis egestas. Ipsum faucibus vitae aliquet nec ullamcorper sit. Porttitor rhoncus dolor purus non enim praesent. Nunc eget lorem dolor sed viverra ipsum nunc. Sed turpis tincidunt id aliquet risus. Hac habitasse platea dictumst quisque sagittis purus sit amet. Ullamcorper malesuada proin libero nunc. Felis bibendum ut tristique et. Id faucibus nisl tincidunt eget. Amet cursus sit amet dictum sit. Integer quis auctor elit sed vulputate mi sit. Quis ipsum suspendisse ultrices gravida dictum fusce ut placerat orci. Feugiat in ante metus dictum at tempor commodo ullamcorper. Ornare arcu dui vivamus arcu felis bibendum.`,
    },
    {
        title: `HOW TO BE A DIGITAL NOMAD IN EUROPE`,
        resim: 'https://www.nomadicmatt.com/wp-content/uploads/2024/01/europe_nomad-760x440.jpeg',
        time: '15 hour',
        content: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquam sem et tortor consequat id porta. Feugiat sed lectus vestibulum mattis ullamcorper velit sed. A diam sollicitudin tempor id eu. Commodo odio aenean sed adipiscing diam donec adipiscing tristique. Nunc pulvinar sapien et ligula ullamcorper malesuada proin libero. Semper auctor neque vitae tempus quam. Ullamcorper eget nulla facilisi etiam dignissim diam quis enim lobortis. Amet tellus cras adipiscing enim eu turpis egestas pretium. Viverra justo nec ultrices dui sapien eget mi proin sed. Auctor elit sed vulputate mi sit.

Donec massa sapien faucibus et molestie. Mollis nunc sed id semper risus in hendrerit gravida rutrum. Tortor at risus viverra adipiscing at in tellus. Sed felis eget velit aliquet sagittis. Suspendisse in est ante in nibh mauris cursus mattis molestie. Suspendisse sed nisi lacus sed viverra. Et malesuada fames ac turpis egestas. Ipsum faucibus vitae aliquet nec ullamcorper sit. Porttitor rhoncus dolor purus non enim praesent. Nunc eget lorem dolor sed viverra ipsum nunc. Sed turpis tincidunt id aliquet risus. Hac habitasse platea dictumst quisque sagittis purus sit amet. Ullamcorper malesuada proin libero nunc. Felis bibendum ut tristique et. Id faucibus nisl tincidunt eget. Amet cursus sit amet dictum sit. Integer quis auctor elit sed vulputate mi sit. Quis ipsum suspendisse ultrices gravida dictum fusce ut placerat orci. Feugiat in ante metus dictum at tempor commodo ullamcorper. Ornare arcu dui vivamus arcu felis bibendum.`,
    },
    {
        title: `THE ULTIMATE GUIDE TO RENTING A CAR IN COSTA RICA`,
        resim: 'https://www.nomadicmatt.com/wp-content/uploads/2024/01/costaricacar1-760x440.jpeg',
        time: '15 hour',
        content: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquam sem et tortor consequat id porta. Feugiat sed lectus vestibulum mattis ullamcorper velit sed. A diam sollicitudin tempor id eu. Commodo odio aenean sed adipiscing diam donec adipiscing tristique. Nunc pulvinar sapien et ligula ullamcorper malesuada proin libero. Semper auctor neque vitae tempus quam. Ullamcorper eget nulla facilisi etiam dignissim diam quis enim lobortis. Amet tellus cras adipiscing enim eu turpis egestas pretium. Viverra justo nec ultrices dui sapien eget mi proin sed. Auctor elit sed vulputate mi sit.

Donec massa sapien faucibus et molestie. Mollis nunc sed id semper risus in hendrerit gravida rutrum. Tortor at risus viverra adipiscing at in tellus. Sed felis eget velit aliquet sagittis. Suspendisse in est ante in nibh mauris cursus mattis molestie. Suspendisse sed nisi lacus sed viverra. Et malesuada fames ac turpis egestas. Ipsum faucibus vitae aliquet nec ullamcorper sit. Porttitor rhoncus dolor purus non enim praesent. Nunc eget lorem dolor sed viverra ipsum nunc. Sed turpis tincidunt id aliquet risus. Hac habitasse platea dictumst quisque sagittis purus sit amet. Ullamcorper malesuada proin libero nunc. Felis bibendum ut tristique et. Id faucibus nisl tincidunt eget. Amet cursus sit amet dictum sit. Integer quis auctor elit sed vulputate mi sit. Quis ipsum suspendisse ultrices gravida dictum fusce ut placerat orci. Feugiat in ante metus dictum at tempor commodo ullamcorper. Ornare arcu dui vivamus arcu felis bibendum.`,
    },
    {
        title: `THE 5 BEST HOTELS IN OAXACA`,
        resim: 'https://www.nomadicmatt.com/wp-content/uploads/2024/01/oaxacahotel2-760x440.jpeg',
        time: '15 hour',
        content: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquam sem et tortor consequat id porta. Feugiat sed lectus vestibulum mattis ullamcorper velit sed. A diam sollicitudin tempor id eu. Commodo odio aenean sed adipiscing diam donec adipiscing tristique. Nunc pulvinar sapien et ligula ullamcorper malesuada proin libero. Semper auctor neque vitae tempus quam. Ullamcorper eget nulla facilisi etiam dignissim diam quis enim lobortis. Amet tellus cras adipiscing enim eu turpis egestas pretium. Viverra justo nec ultrices dui sapien eget mi proin sed. Auctor elit sed vulputate mi sit.

Donec massa sapien faucibus et molestie. Mollis nunc sed id semper risus in hendrerit gravida rutrum. Tortor at risus viverra adipiscing at in tellus. Sed felis eget velit aliquet sagittis. Suspendisse in est ante in nibh mauris cursus mattis molestie. Suspendisse sed nisi lacus sed viverra. Et malesuada fames ac turpis egestas. Ipsum faucibus vitae aliquet nec ullamcorper sit. Porttitor rhoncus dolor purus non enim praesent. Nunc eget lorem dolor sed viverra ipsum nunc. Sed turpis tincidunt id aliquet risus. Hac habitasse platea dictumst quisque sagittis purus sit amet. Ullamcorper malesuada proin libero nunc. Felis bibendum ut tristique et. Id faucibus nisl tincidunt eget. Amet cursus sit amet dictum sit. Integer quis auctor elit sed vulputate mi sit. Quis ipsum suspendisse ultrices gravida dictum fusce ut placerat orci. Feugiat in ante metus dictum at tempor commodo ullamcorper. Ornare arcu dui vivamus arcu felis bibendum.`,
    },
    {
        title: `THE 6 BEST HOSTELS IN CUSCO`,
        resim: 'https://www.nomadicmatt.com/wp-content/uploads/2024/01/besthostelscusco-760x440.jpg',
        time: '15 hour',
        content: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquam sem et tortor consequat id porta. Feugiat sed lectus vestibulum mattis ullamcorper velit sed. A diam sollicitudin tempor id eu. Commodo odio aenean sed adipiscing diam donec adipiscing tristique. Nunc pulvinar sapien et ligula ullamcorper malesuada proin libero. Semper auctor neque vitae tempus quam. Ullamcorper eget nulla facilisi etiam dignissim diam quis enim lobortis. Amet tellus cras adipiscing enim eu turpis egestas pretium. Viverra justo nec ultrices dui sapien eget mi proin sed. Auctor elit sed vulputate mi sit.

Donec massa sapien faucibus et molestie. Mollis nunc sed id semper risus in hendrerit gravida rutrum. Tortor at risus viverra adipiscing at in tellus. Sed felis eget velit aliquet sagittis. Suspendisse in est ante in nibh mauris cursus mattis molestie. Suspendisse sed nisi lacus sed viverra. Et malesuada fames ac turpis egestas. Ipsum faucibus vitae aliquet nec ullamcorper sit. Porttitor rhoncus dolor purus non enim praesent. Nunc eget lorem dolor sed viverra ipsum nunc. Sed turpis tincidunt id aliquet risus. Hac habitasse platea dictumst quisque sagittis purus sit amet. Ullamcorper malesuada proin libero nunc. Felis bibendum ut tristique et. Id faucibus nisl tincidunt eget. Amet cursus sit amet dictum sit. Integer quis auctor elit sed vulputate mi sit. Quis ipsum suspendisse ultrices gravida dictum fusce ut placerat orci. Feugiat in ante metus dictum at tempor commodo ullamcorper. Ornare arcu dui vivamus arcu felis bibendum.`,
    },

];

export default popular;