const spor = [
    {
        title: `SportsBlog newsletter 11/20: Vivaaaa Las Vegas!`,
        resim: 'https://blogstorage.s3.amazonaws.com/uploads/cache/e6/1c/e61c0dbe386dd4ad14ec842c91cce3a8.jpg',
        time: '1 hour',
        content: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquam sem et tortor consequat id porta. Feugiat sed lectus vestibulum mattis ullamcorper velit sed. A diam sollicitudin tempor id eu. Commodo odio aenean sed adipiscing diam donec adipiscing tristique. Nunc pulvinar sapien et ligula ullamcorper malesuada proin libero. Semper auctor neque vitae tempus quam. Ullamcorper eget nulla facilisi etiam dignissim diam quis enim lobortis. Amet tellus cras adipiscing enim eu turpis egestas pretium. Viverra justo nec ultrices dui sapien eget mi proin sed. Auctor elit sed vulputate mi sit.

        Donec massa sapien faucibus et molestie. Mollis nunc sed id semper risus in hendrerit gravida rutrum. Tortor at risus viverra adipiscing at in tellus. Sed felis eget velit aliquet sagittis. Suspendisse in est ante in nibh mauris cursus mattis molestie. Suspendisse sed nisi lacus sed viverra. Et malesuada fames ac turpis egestas. Ipsum faucibus vitae aliquet nec ullamcorper sit. Porttitor rhoncus dolor purus non enim praesent. Nunc eget lorem dolor sed viverra ipsum nunc. Sed turpis tincidunt id aliquet risus. Hac habitasse platea dictumst quisque sagittis purus sit amet. Ullamcorper malesuada proin libero nunc. Felis bibendum ut tristique et. Id faucibus nisl tincidunt eget. Amet cursus sit amet dictum sit. Integer quis auctor elit sed vulputate mi sit. Quis ipsum suspendisse ultrices gravida dictum fusce ut placerat orci. Feugiat in ante metus dictum at tempor commodo ullamcorper. Ornare arcu dui vivamus arcu felis bibendum.`,
    },
    {
        title: `Browns set to sign veteran QB Joe Flacco to practice squad`,
        resim: 'https://blogstorage.s3.amazonaws.com/uploads/cache/f2/0b/f20b0afd0fb1cb21eb09017d2501c5cd.jpg',
        time: '4 hour',
        content: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquam sem et tortor consequat id porta. Feugiat sed lectus vestibulum mattis ullamcorper velit sed. A diam sollicitudin tempor id eu. Commodo odio aenean sed adipiscing diam donec adipiscing tristique. Nunc pulvinar sapien et ligula ullamcorper malesuada proin libero. Semper auctor neque vitae tempus quam. Ullamcorper eget nulla facilisi etiam dignissim diam quis enim lobortis. Amet tellus cras adipiscing enim eu turpis egestas pretium. Viverra justo nec ultrices dui sapien eget mi proin sed. Auctor elit sed vulputate mi sit.

        Donec massa sapien faucibus et molestie. Mollis nunc sed id semper risus in hendrerit gravida rutrum. Tortor at risus viverra adipiscing at in tellus. Sed felis eget velit aliquet sagittis. Suspendisse in est ante in nibh mauris cursus mattis molestie. Suspendisse sed nisi lacus sed viverra. Et malesuada fames ac turpis egestas. Ipsum faucibus vitae aliquet nec ullamcorper sit. Porttitor rhoncus dolor purus non enim praesent. Nunc eget lorem dolor sed viverra ipsum nunc. Sed turpis tincidunt id aliquet risus. Hac habitasse platea dictumst quisque sagittis purus sit amet. Ullamcorper malesuada proin libero nunc. Felis bibendum ut tristique et. Id faucibus nisl tincidunt eget. Amet cursus sit amet dictum sit. Integer quis auctor elit sed vulputate mi sit. Quis ipsum suspendisse ultrices gravida dictum fusce ut placerat orci. Feugiat in ante metus dictum at tempor commodo ullamcorper. Ornare arcu dui vivamus arcu felis bibendum.`,
    },
    {
        title: `Dan Campbell: "Get Your Diapers Ready"`,
        resim: 'https://blogstorage.s3.amazonaws.com/uploads/cache/0d/32/0d32e9bdbadc9d1d91922bfacc3d9850.jpg',
        time: '5 hour',
        content: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquam sem et tortor consequat id porta. Feugiat sed lectus vestibulum mattis ullamcorper velit sed. A diam sollicitudin tempor id eu. Commodo odio aenean sed adipiscing diam donec adipiscing tristique. Nunc pulvinar sapien et ligula ullamcorper malesuada proin libero. Semper auctor neque vitae tempus quam. Ullamcorper eget nulla facilisi etiam dignissim diam quis enim lobortis. Amet tellus cras adipiscing enim eu turpis egestas pretium. Viverra justo nec ultrices dui sapien eget mi proin sed. Auctor elit sed vulputate mi sit.

        Donec massa sapien faucibus et molestie. Mollis nunc sed id semper risus in hendrerit gravida rutrum. Tortor at risus viverra adipiscing at in tellus. Sed felis eget velit aliquet sagittis. Suspendisse in est ante in nibh mauris cursus mattis molestie. Suspendisse sed nisi lacus sed viverra. Et malesuada fames ac turpis egestas. Ipsum faucibus vitae aliquet nec ullamcorper sit. Porttitor rhoncus dolor purus non enim praesent. Nunc eget lorem dolor sed viverra ipsum nunc. Sed turpis tincidunt id aliquet risus. Hac habitasse platea dictumst quisque sagittis purus sit amet. Ullamcorper malesuada proin libero nunc. Felis bibendum ut tristique et. Id faucibus nisl tincidunt eget. Amet cursus sit amet dictum sit. Integer quis auctor elit sed vulputate mi sit. Quis ipsum suspendisse ultrices gravida dictum fusce ut placerat orci. Feugiat in ante metus dictum at tempor commodo ullamcorper. Ornare arcu dui vivamus arcu felis bibendum.`,
    },
    {
        title: `Patriots Stock Report: 3 up, 3 down`,
        resim: 'https://blogstorage.s3.amazonaws.com/uploads/cache/13/b1/13b1124281af41a191d4a568c555e003.jpg',
        time: '25 hour',
        content: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquam sem et tortor consequat id porta. Feugiat sed lectus vestibulum mattis ullamcorper velit sed. A diam sollicitudin tempor id eu. Commodo odio aenean sed adipiscing diam donec adipiscing tristique. Nunc pulvinar sapien et ligula ullamcorper malesuada proin libero. Semper auctor neque vitae tempus quam. Ullamcorper eget nulla facilisi etiam dignissim diam quis enim lobortis. Amet tellus cras adipiscing enim eu turpis egestas pretium. Viverra justo nec ultrices dui sapien eget mi proin sed. Auctor elit sed vulputate mi sit.

        Donec massa sapien faucibus et molestie. Mollis nunc sed id semper risus in hendrerit gravida rutrum. Tortor at risus viverra adipiscing at in tellus. Sed felis eget velit aliquet sagittis. Suspendisse in est ante in nibh mauris cursus mattis molestie. Suspendisse sed nisi lacus sed viverra. Et malesuada fames ac turpis egestas. Ipsum faucibus vitae aliquet nec ullamcorper sit. Porttitor rhoncus dolor purus non enim praesent. Nunc eget lorem dolor sed viverra ipsum nunc. Sed turpis tincidunt id aliquet risus. Hac habitasse platea dictumst quisque sagittis purus sit amet. Ullamcorper malesuada proin libero nunc. Felis bibendum ut tristique et. Id faucibus nisl tincidunt eget. Amet cursus sit amet dictum sit. Integer quis auctor elit sed vulputate mi sit. Quis ipsum suspendisse ultrices gravida dictum fusce ut placerat orci. Feugiat in ante metus dictum at tempor commodo ullamcorper. Ornare arcu dui vivamus arcu felis bibendum.`,
    },
    {
        title: `Willie Mays Career Home Runs By Park`,
        resim: 'https://blogstorage.s3.amazonaws.com/uploads/cache/84/97/84973348193deea578775e0f7babc03b.jpg',
        time: '75 hour',
        content: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquam sem et tortor consequat id porta. Feugiat sed lectus vestibulum mattis ullamcorper velit sed. A diam sollicitudin tempor id eu. Commodo odio aenean sed adipiscing diam donec adipiscing tristique. Nunc pulvinar sapien et ligula ullamcorper malesuada proin libero. Semper auctor neque vitae tempus quam. Ullamcorper eget nulla facilisi etiam dignissim diam quis enim lobortis. Amet tellus cras adipiscing enim eu turpis egestas pretium. Viverra justo nec ultrices dui sapien eget mi proin sed. Auctor elit sed vulputate mi sit.

        Donec massa sapien faucibus et molestie. Mollis nunc sed id semper risus in hendrerit gravida rutrum. Tortor at risus viverra adipiscing at in tellus. Sed felis eget velit aliquet sagittis. Suspendisse in est ante in nibh mauris cursus mattis molestie. Suspendisse sed nisi lacus sed viverra. Et malesuada fames ac turpis egestas. Ipsum faucibus vitae aliquet nec ullamcorper sit. Porttitor rhoncus dolor purus non enim praesent. Nunc eget lorem dolor sed viverra ipsum nunc. Sed turpis tincidunt id aliquet risus. Hac habitasse platea dictumst quisque sagittis purus sit amet. Ullamcorper malesuada proin libero nunc. Felis bibendum ut tristique et. Id faucibus nisl tincidunt eget. Amet cursus sit amet dictum sit. Integer quis auctor elit sed vulputate mi sit. Quis ipsum suspendisse ultrices gravida dictum fusce ut placerat orci. Feugiat in ante metus dictum at tempor commodo ullamcorper. Ornare arcu dui vivamus arcu felis bibendum.`,
    },
    {
        title: `Trevon Diggs makes it clear that his brother, Stefon, should leave Buffalo!`,
        resim: 'https://blogstorage.s3.amazonaws.com/uploads/cache/3c/ef/3cef542ad277a34260804cc39be607c8.jpg',
        time: '95 hour',
        content: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquam sem et tortor consequat id porta. Feugiat sed lectus vestibulum mattis ullamcorper velit sed. A diam sollicitudin tempor id eu. Commodo odio aenean sed adipiscing diam donec adipiscing tristique. Nunc pulvinar sapien et ligula ullamcorper malesuada proin libero. Semper auctor neque vitae tempus quam. Ullamcorper eget nulla facilisi etiam dignissim diam quis enim lobortis. Amet tellus cras adipiscing enim eu turpis egestas pretium. Viverra justo nec ultrices dui sapien eget mi proin sed. Auctor elit sed vulputate mi sit.

        Donec massa sapien faucibus et molestie. Mollis nunc sed id semper risus in hendrerit gravida rutrum. Tortor at risus viverra adipiscing at in tellus. Sed felis eget velit aliquet sagittis. Suspendisse in est ante in nibh mauris cursus mattis molestie. Suspendisse sed nisi lacus sed viverra. Et malesuada fames ac turpis egestas. Ipsum faucibus vitae aliquet nec ullamcorper sit. Porttitor rhoncus dolor purus non enim praesent. Nunc eget lorem dolor sed viverra ipsum nunc. Sed turpis tincidunt id aliquet risus. Hac habitasse platea dictumst quisque sagittis purus sit amet. Ullamcorper malesuada proin libero nunc. Felis bibendum ut tristique et. Id faucibus nisl tincidunt eget. Amet cursus sit amet dictum sit. Integer quis auctor elit sed vulputate mi sit. Quis ipsum suspendisse ultrices gravida dictum fusce ut placerat orci. Feugiat in ante metus dictum at tempor commodo ullamcorper. Ornare arcu dui vivamus arcu felis bibendum.`,
    },
    {
        title: `
        Shamar Joseph alone won’t revive West Indies but memories will remain`,
        resim: 'https://i.guim.co.uk/img/media/606f69cf6549b0f5d80b04dfc801c38a1d48a48e/0_50_2266_1360/master/2266.jpg?width=1900&dpr=1&s=none',
        time: '115 hour',
        content: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquam sem et tortor consequat id porta. Feugiat sed lectus vestibulum mattis ullamcorper velit sed. A diam sollicitudin tempor id eu. Commodo odio aenean sed adipiscing diam donec adipiscing tristique. Nunc pulvinar sapien et ligula ullamcorper malesuada proin libero. Semper auctor neque vitae tempus quam. Ullamcorper eget nulla facilisi etiam dignissim diam quis enim lobortis. Amet tellus cras adipiscing enim eu turpis egestas pretium. Viverra justo nec ultrices dui sapien eget mi proin sed. Auctor elit sed vulputate mi sit.

        Donec massa sapien faucibus et molestie. Mollis nunc sed id semper risus in hendrerit gravida rutrum. Tortor at risus viverra adipiscing at in tellus. Sed felis eget velit aliquet sagittis. Suspendisse in est ante in nibh mauris cursus mattis molestie. Suspendisse sed nisi lacus sed viverra. Et malesuada fames ac turpis egestas. Ipsum faucibus vitae aliquet nec ullamcorper sit. Porttitor rhoncus dolor purus non enim praesent. Nunc eget lorem dolor sed viverra ipsum nunc. Sed turpis tincidunt id aliquet risus. Hac habitasse platea dictumst quisque sagittis purus sit amet. Ullamcorper malesuada proin libero nunc. Felis bibendum ut tristique et. Id faucibus nisl tincidunt eget. Amet cursus sit amet dictum sit. Integer quis auctor elit sed vulputate mi sit. Quis ipsum suspendisse ultrices gravida dictum fusce ut placerat orci. Feugiat in ante metus dictum at tempor commodo ullamcorper. Ornare arcu dui vivamus arcu felis bibendum.`,
    },
    {
        title: `Michelle Mone’s big Grand National hope may be prevented from running`,
        resim: 'https://i.guim.co.uk/img/media/9158d7c64b8966100880038d2b93f660cdafd7b1/0_363_2762_1658/master/2762.jpg?width=1900&dpr=1&s=none',
        time: '125 hour',
        content: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquam sem et tortor consequat id porta. Feugiat sed lectus vestibulum mattis ullamcorper velit sed. A diam sollicitudin tempor id eu. Commodo odio aenean sed adipiscing diam donec adipiscing tristique. Nunc pulvinar sapien et ligula ullamcorper malesuada proin libero. Semper auctor neque vitae tempus quam. Ullamcorper eget nulla facilisi etiam dignissim diam quis enim lobortis. Amet tellus cras adipiscing enim eu turpis egestas pretium. Viverra justo nec ultrices dui sapien eget mi proin sed. Auctor elit sed vulputate mi sit.

        Donec massa sapien faucibus et molestie. Mollis nunc sed id semper risus in hendrerit gravida rutrum. Tortor at risus viverra adipiscing at in tellus. Sed felis eget velit aliquet sagittis. Suspendisse in est ante in nibh mauris cursus mattis molestie. Suspendisse sed nisi lacus sed viverra. Et malesuada fames ac turpis egestas. Ipsum faucibus vitae aliquet nec ullamcorper sit. Porttitor rhoncus dolor purus non enim praesent. Nunc eget lorem dolor sed viverra ipsum nunc. Sed turpis tincidunt id aliquet risus. Hac habitasse platea dictumst quisque sagittis purus sit amet. Ullamcorper malesuada proin libero nunc. Felis bibendum ut tristique et. Id faucibus nisl tincidunt eget. Amet cursus sit amet dictum sit. Integer quis auctor elit sed vulputate mi sit. Quis ipsum suspendisse ultrices gravida dictum fusce ut placerat orci. Feugiat in ante metus dictum at tempor commodo ullamcorper. Ornare arcu dui vivamus arcu felis bibendum.`,
    },
    
];

export default spor;